version: '3.4'

services:
  htbupdatesdiscordbot:
    image: htbupdatesdiscordbot
    build:
      context: .
      dockerfile: HTB Updates Discord Bot/Dockerfile
    restart: always
  htbupdatesfrontend:
    image: htbupdatesfrontend
    build:
      context: .
      dockerfile: htb_updates_frontend/Dockerfile
    ports:
      - 8080:80
    restart: always
  htbupdatesbackend:
    image: htbupdatesbackend
    build:
      context: .
      dockerfile: htb_updates_backend/Dockerfile
    restart: always