name: Production Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: apps-azure
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: sudo docker compose build
    - name: Run
      run: sudo docker compose up -d --force-recreate